book/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    # url(r'add/$', add_post),
    # url(r'edit/(?P<id>\d+)$', edit_post),
]

checkout/urls.py
from django.conf.urls import url, include
from .views import checkout

urlpatterns = [
    url(r'^$', checkout, name='checkout_link')
]

issue_tracker/urls.py
from django.conf.urls import url
from django.contrib import admin
from issuetracker_app.views import hello



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', hello)

]

online_bookstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings 
from django.conf.urls.static import static 

# from book.views import hello
from book import urls as book_urls
from authentication import urls as authentication_urls
from shopping_cart import urls as shopping_cart_urls
from checkout import urls as checkout_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include(authentication_urls.urlpatterns)),
    url(r'^$', include(book_urls.urlpatterns)),
    url(r'^shopping_cart/', include(shopping_cart_urls.urlpatterns)),
    url(r'^checkout/', include(checkout_urls.urlpatterns)),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book

# Create your models here.
class Order(models.Model):
    
    ordered_by = models.ForeignKey(User, on_delete = models.CASCADE, related_name='orders')
    stripe_token = models.CharField(max_length=1000, blank=False)
    purchased_at = models.DateTimeField(blank=False)
    name = models.CharField(max_length=255, blank=False)
    address =models.CharField(max_length=255, blank=False)
    
    def __str__(self):
        return "Order - #" + str(self.id)
    
class OrderLineItem(models.Model):
    
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name = 'orders')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name = 'order_line_items')
    quantity = models.IntegerField()
    def __str__(self):
        return "Order #{} - Product #{}".format(self.order_id, self.book_id)

checkout/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('name', 'address')

class PaymentForm(forms.Form):

    MONTH_CHOICES = [(i, i) for i in range(1, 13)]
    YEAR_CHOICES = [(i, i) for i in range(2019, 2036)]

    credit_card_number = forms.CharField(label='Credit card number', required=False)
    cvv = forms.CharField(label='Security code (CVV)', required=False)
    expiry_month = forms.ChoiceField(label='Month', choices=MONTH_CHOICES, required=False)
    expiry_year = forms.ChoiceField(label='Year', choices=YEAR_CHOICES, required=False)
    stripe_id = forms.CharField(widget=forms.HiddenInput)

checkout/views.py
from django.shortcuts import render, HttpResponse
from django.conf import settings
from .forms import OrderForm, PaymentForm
from django.utils import timezone
from book.models import Book
from .models import Order, OrderLineItem
from django.core.mail import send_mail
from authentication.forms import RegisterUserForm
import authentication.views
import stripe
import os


# Create your views here.
def checkout(request):
    # this is to show the form
    if request.method == 'GET':
        cart = request.session.get('cart', {})
        order_form = OrderForm()
        payment_form = PaymentForm()
        return render(request, 'checkout.html', {
            'cart': cart, 
            'order_form':order_form,
            'payment_form':payment_form,
            'stripe_publishable_key':settings.STRIPE_PUBLISHABLE_KEY
        })
    else:
        # set the secret key for Stripe
        stripe.api_key = settings.STRIPE_SECRET_KEY
        
        # to process the post via POST
        cart = request.session.get('cart', {})
        total_cost = 0
        for cart_item in cart.values():
            total_cost = cart_item['quantity'] * float(cart_item['product']['price'])
           
        order_form = OrderForm(request.POST)
        payment_form = PaymentForm(request.POST) 
        
        if order_form.is_valid() and payment_form.is_valid():
            order = order_form.save(commit=False)
            order.stripe_token = request.POST.get('stripe_id')
            order.purchased_at = timezone.now()
            order.ordered_by = request.user
            order.save()
            
            for cart_item in cart.values():
                book_id = cart_item['product']['id']
                book = Book.objects.get(pk=book_id)
                order_line_item = OrderLineItem(
                    book = book,
                    order = order,
                    quantity = cart_item['quantity']
                )
                order_line_item.save()
                
            try:
                customer = stripe.Charge.create(
                    amount = int(total_cost * 100),
                    currency = "sgd",
                    description = "Order ID #" + str(order.id),
                    source= order.stripe_token
                    )
            except stripe.error.CardError as e: 
                print (e)
                return HttpResponse("Card problem")
                
            if customer.paid:
                subject = "Your invoice for your order #" + str(order.id)
                message = "Your order has been processed and will be shipped to you shortly."
                email_from = settings.EMAIL_HOST_USER
                
                # send_to = ['mannagoodies@gmail.com']
                send_to = [request.user.email]
                send_mail(subject, message, email_from, send_to)
                return  HttpResponse("Payment Successful")
            else:
                return HttpResponse("Payment Failed")
            
        else:
            print(order_form.is_valid())
            print(payment_form.is_valid())
            print(payment_form.errors)

checkout/templates/checkout.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{%block title%}{%endblock%}</title>
  </head>
  <body>
      <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index1' %}">
          Online Bookstore
        </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li>
                    {% if user.is_authenticated %}
                    <div style="color:white">Welcome, {{ user.username }}
                    <a style="color:white" href="{% url 'logout_link' %}" class='ml-4 mr-4'>Log Out</a>
                    </div>
                    {% else %}
                    <div style="color:white" class='ml-4 mr-4'>Please Log In</div>
                    {% endif %}
            </li>
        </ul>
      </div>
    </div>
  </nav>
  
      <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav d-flex align-items-center">
          {% with url_name=request.resolver_match.url_name %}
          <li class="{% if url_name == 'index1' %}active{% endif %}">
            <a class="nav-link" href="{% url 'index1' %}">Home</a>
          </li>
          <li class="{% if url_name == 'view_cart' %}active{% endif %}">
            <a class="nav-link" href="{% url 'view_cart' %}">Shopping Cart</a>
          </li>
          <li class="{% if url_name == 'manage_authors' %}active{% endif %}">
            <a class="nav-link" href="{% url 'manage_authors' %}">Manage Authors</a>
          </li>
          <li class="{% if url_name == 'manage_genres' %}active{% endif %}">
            <a class="nav-link" href="{% url 'manage_genres' %}">Manage Genres</a>
          </li>
          <li class="{% if url_name == 'add' %}active{% endif %}">
            <a class="nav-link" href="{% url 'add' %}">Add Book</a>
          </li>
          {% endwith %}
        </ul>
      </div>
    </div>
  </nav>
<br>  
    {% if messages %}
    <div class='container'>
        <ul>
            {% for m in messages %}
            <li>{{m}}</li>
            {% endfor %}
        </ul>
    </div>    
    {% endif %}
<div class='container'>
<h1>Checkout</h1>
<p>
    Please check that you want to purchase the items below because there will be no refund.
</p>
<ul>
    {% for key,value in cart.items %}
    <li>{{value.product.title}}
    by {{value.product.author_name}}
    <br>Price: ${{value.product.price}}    
    <br>Quantity: {{value.quantity}}
    <br>
    {% endfor %}
</ul>

    <form method="POST" id='payment-form'>
    {% csrf_token %}
    {{ order_form|crispy }}
    
    {{ payment_form|crispy }}
    
    <input type='submit'>
</form>
<br>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
/* global $ */
$(function(){

    $('#payment-form').submit(function(event){
        // Prevent the default of behaviour of clicking on the form's submit button
        // In general, preventDefault() can be used to override the browser's defualt behaviour
        event.preventDefault();
        
        let stripe_publishable_key = '{{stripe_publishable_key }}';
       
        /* global Stripe */
        Stripe.publishableKey = stripe_publishable_key;
        // This is to create a card object according to the Stripe's specification
        var card = {
            number: $("#id_credit_card_number").val(),
            expMonth: $("#id_expiry_month").val(),
            expYear: $("#id_expiry_year").val(),
            cvc: $("#id_cvv").val()
        };
        let form = this;
        
        Stripe.createToken(card, function(status, response){
            if (status == 200) {
                $('#id_credit_card_number').removeAttr('name');
                $('#id_cvv').removeAttr('name');
                $("#id_expiry_month").removeAttr('name');
                $("#id_expiry_year").removeAttr('name');
                $("#id_stripe_id").val(response.id);
                form.submit();
            }  else {
                alert("Credit card problem");
            }
        });
    })
});
</script>
  </body>
</html>